<link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Actor&amp;display=swap">
<link rel="stylesheet" href="{{asset('css/bootstrap-icons.css')}}">
<link rel="stylesheet" href="{{asset('css/Font%20Awesome%205%20Brands.css')}}">
<link rel="stylesheet" href="{{asset('css/Font%20Awesome%205%20Free.css')}}">
<link rel="stylesheet" href="{{asset('css/Font%20Awesome%206%20Brands.css')}}">
<link rel="stylesheet" href="{{asset('css/Font%20Awesome%206%20Free.css')}}">
<link rel="stylesheet" href="{{asset('css/FontAwesome.css')}}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100i,300,300i,400,700,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans:300,400,500,600,700,800&amp;display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:400,600,800">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,400i,700,700i">
<link rel="stylesheet" href="{{asset('css/swiper-icons.css')}}">
<link rel="stylesheet" href="{{asset('fonts/fontawesome-all.min.css')}}">
<link rel="stylesheet" href="{{asset('css/aos.min.css')}}">
<link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('css/bootstrap-icons.min.css')}}">
<link rel="stylesheet" href="{{asset('css/aos.css')}}">
<link rel="stylesheet" href="{{asset('css/all.min.css')}}">
<link rel="stylesheet" href="{{asset('css/swiper-bundle.min.css')}}">
<link rel="stylesheet" href="{{asset('css/main.css')}}">
<link rel="stylesheet" href="{{asset('css/Blog-Detail-App.css')}}">
<link rel="stylesheet" href="{{asset('css/Bootstrap-4---Photo-Gallery.css')}}">
<link rel="stylesheet" href="{{asset('css/BOOTSTRAP-IMAGE-HOVER.css')}}">
<link rel="stylesheet" href="{{asset('css/logo-slider.css')}}">
<link rel="stylesheet" href="{{asset('css/Scroll-To-Top.css')}}">
<link rel="stylesheet" href="{{asset('css/Videos-in-rows-2-and-3-videos-per-row.css')}}">
<link rel="stylesheet" href="{{asset('css/Whatsapp-flotating-button.css')}}">
